site_name: LiuTianBa7 's Blog
site_url: https://liutianba7.github.io # 建议加上你的域名
repo_url: https://github.com/liutianba7/liutianba7.github.io
repo_name: blog
edit_uri: edit/main/docs/  # 允许直接从网页跳转到 GitHub 编辑源码



nav:
  - Welcome: index.md
  - Java:
    - ssm: ./java/ssm.md
    - springboot: ./java/springboot.md
  - Python:
      - langchain: ./python/Ai/langchain.md
      - pytorch: ./python/Ai/pytorch.md
      - fastapi: ./python/Web/fastapi.md
  - Frontend:
      - js: ./frontend/js.md
      - vue3: ./frontend/vue3.md
  - Bagu:
      - 八股复习路线: ./interview/index.md
      - java基础: ./interview/points/java基础.md
      - ssm: ./interview/points/ssm.md
      - spring[boot|cloud]: ./interview/points/springboot+Cloud.md
      - mysql: ./interview/points/mysql.md
      - redis: ./interview/points/redis.md
      - elasticsearch: ./interview/points/es.md
      - rmq: ./interview/points/rmq.md
      - seata: ./interview/points/seata.md
      - 设计模式: ./interview/points/设计模式.md
  - Journal:
      - 202602: ./journal/2026-02.md
  - Tools:
      - git: ./tools/git.md
      - docker: ./tools/docker.md
  - Middleware:
    - mysql 基础: ./middleware/mysql基础.md
    - mysql 高级: ./middleware/mysql高级.md
    - redis: ./middleware/redis.md
    - minio: ./middleware/minio.md
  - Linux:
      - basic: ./linux/basic.md

use_directory_urls: false

plugins:
  - search


theme:
  name: material
  language: zh
  # 1. 调色盘：支持深浅模式自动切换
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white    # 极简白背景 网站头部颜色
      accent: indigo    # 链接和交互色
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black    # 深色模式
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式

  # 2. 界面细节优化
  features:
    - navigation.tabs              # 顶部横向菜单栏（适合分类多时）
    - navigation.tracking          # 滚动时自动定位侧边栏
    - navigation.top               # 返回顶部按钮
    - search.suggest               # 搜索输入补全
    - search.highlight             # 搜索结果高亮
    - content.code.copy            # 代码块一键复制按钮

  icon:
    logo: material/cat
    repo: fontawesome/brands/github  # 这一行是关键，强制指定右上角为小猫
    favicon: material/cat          # 浏览器标签页的小图标

copyright: |
  Copyright &copy; 2026 LiuTianBa7 

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:   # 数学公式支持
      generic: true


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js